<a href="https://colab.research.google.com/github/TheAcoff/Notebook-Alura/blob/main/Python%20para%20Data%20Science/Projetos%20Basicos/Banco_de_Dados01_Banco_e_Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

O exercício propõe a criação de um banco de dados de uma instituição financeira usando a base: do [arquivo CSV](https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv).

In [1]:
#Importando as bibliotecas
import pandas as pd
import sqlalchemy
#Atualizando a versão do sqlalchemy para compatbilidade
!pip install --upgrade 'sqlalchemy<2.0'

In [2]:
from sqlalchemy import create_engine, MetaData, Table, inspect

Importando os dados para um DataFrame e fazendo as primeiras análises.

In [3]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
df = pd.read_csv(url)
df.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

In [4]:
df.shape #Formato do DataFrame

(438463, 11)

In [5]:
df.info() #Informações das variáveis

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438463 entries, 0 to 438462
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   ID_Cliente          438463 non-null  int64  
 1   Idade               438463 non-null  int64  
 2   Grau_escolaridade   438463 non-null  object 
 3   Estado_civil        438463 non-null  object 
 4   Tamanho_familia     438463 non-null  int64  
 5   Categoria_de_renda  438463 non-null  object 
 6   Ocupacao            438463 non-null  object 
 7   Anos_empregado      438463 non-null  int64  
 8   Rendimento_anual    438463 non-null  float64
 9   Tem_carro           438463 non-null  int64  
 10  Moradia             438463 non-null  object 
dtypes: float64(1), int64(5), object(5)
memory usage: 36.8+ MB


Verificando se há a existência de valores não numériocs

In [6]:
df.isnull().sum()

ID_Cliente            0
Idade                 0
Grau_escolaridade     0
Estado_civil          0
Tamanho_familia       0
Categoria_de_renda    0
Ocupacao              0
Anos_empregado        0
Rendimento_anual      0
Tem_carro             0
Moradia               0
dtype: int64

Criando o banco de dados

In [7]:
engine = create_engine('sqlite:///:memory:')

Importando o DataFrame para o Banco de Dados

In [8]:
df.to_sql('clientes', engine, index=False)

438463

Verificando na base de dados se há o df

In [9]:
inspector = inspect(engine)
inspector.get_table_names()

['clientes']

In [10]:
querry = 'SELECT * FROM clientes'
pd.read_sql(querry,engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

---
Com a base de dados criada, é pedida algumas atualizações:
1. Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.

In [11]:
querry = 'UPDATE clientes SET Rendimento_Anual = 300000 WHERE ID_Cliente = 6840104'
with engine.connect() as conn:
	conn.execute(querry)

<ipython-input-11-99604dcb7196>:3: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  conn.execute(querry)


Conferimos o registro do cliente 6840104

In [12]:
querry = 'SELECT * FROM clientes WHERE ID_Cliente = 6840104'
pd.read_sql(querry,engine)

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
0     6840104     62      Ensino médio   Divorciado                1   

  Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0        Pensionista    Outro               0          300000.0          0   

                    Moradia  
0  Casa/apartamento próprio

2. Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

In [13]:
querry = 'DELETE FROM clientes WHERE ID_Cliente = 5008809'
with engine.connect() as conn:
	conn.execute(querry)

In [14]:
querry = 'SELECT * FROM clientes WHERE ID_Cliente = 5008809'
pd.read_sql(querry,engine)

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

3. Criar um novo registro de cliente seguindo as especificações abaixo:
ID_Cliente: 6850985
Idade: 33
Grau_escolaridade: Doutorado
Estado_civil: Solteiro
Tamanho_familia: 1
Categoria_de_renda: Empregado
Ocupacao: TI
Anos_empregado: 2
Rendimento_anual: 290000
Tem_carro: 0
Moradia: Casa/apartamento próprio

In [15]:
querry = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) VALUES (6850985,33,"Doutorado","Solteiro",1,"Empregado","TI",2,290000,0,"Casa/apartamento proprio")'
with engine.connect() as conn:
	conn.execute(querry)

In [16]:
querry = 'SELECT * FROM clientes WHERE ID_Cliente = 6850985'
pd.read_sql(querry,engine)

ID_Cliente  Idade Grau_escolaridade Estado_civil  Tamanho_familia  \
0     6850985     33         Doutorado     Solteiro                1   

  Categoria_de_renda Ocupacao  Anos_empregado  Rendimento_anual  Tem_carro  \
0          Empregado       TI               2          290000.0          0   

                    Moradia  
0  Casa/apartamento proprio